### PR TITLE
Fixes to drush installation & forcing Drupal 7.x

### PR DESCRIPTION
**Pull request by jeffreyd**
Code to fix drush installation since they stopped distributing via pear and installs in pre_build via composer and forcing Drupal 7.x since 8.x has other problems with this quickstart.  This is dependent upon [this pull request](https://github.com/openshift/origin-server/pull/6339) to the openshift-origin-server that puts the composer installation directory into $PATH.  Also added verbiage to the readme to make it clear that this installs Drupal 7.x

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1291905

**Comment by dinhxuanvu** [comment]
This PR is for issue #31 
@bparees for review/merge. Thank you :)

**Comment by dinhxuanvu** [comment]
BTW, I'm not sure who is qualified to review and merge this PR so Ben if you know someone, please tag them as you will. Thanks.

**Comment by bparees** [comment]
at a minimum you're going to need to squash the commits.

otherwise, @abhgupta someone on your team want to review this?

**Comment by dinhxuanvu** [comment]
@bparees My team can review it but unfortunately, we don't have merge permission on this repo. I guess we can review and give it a thumb-up. Then, you can merge it. Would that be a good idea?

**Comment by bparees** [comment]
@dinhxuanvu that's fine

**Comment by dinhxuanvu** [comment]
@jeffreyd Hey Jeffrey, thank for the work on the PR. Even though it looks good to me, I would like to ask if you squash all of commits into one. It would make the PR easy to be reviewed and keep a clean history as well. Thanks :)

**Comment by dinhxuanvu** [comment]
@Miciah @tiwillia for review and merge

**Comment by tiwillia** [comment]
It looks like there may be some issues with this. I tested using the latest origin-server, after the latest php PR was merged:
```
# rhc app-create drupal2 php-5.3 mysql-5.1 cron --from-code=https://github.com/jeffreyd/drupal-quickstart
Using cron-1.4 (Cron 1.4) for 'cron'

Application Options
-------------------
Domain:      admin
Cartridges:  php-5.3, mysql-5.1, cron-1.4
Source Code: https://github.com/jeffreyd/drupal-quickstart
Gear Size:   default
Scaling:     no

Creating application 'drupal2' ... 
The initial build for the application failed: Shell command '/sbin/runuser -s /bin/sh 5670889708cfed337200001b -c "exec /usr/bin/runcon
'unconfined_u:system_r:openshift_t:s0:c0,c1000' /bin/sh -c \"gear postreceive --init >> /tmp/initial-build.log 2>&1\""' returned an error. rc=255

.Last 10 kB of build output:
Stopping Cron cartridge
Stopping MySQL 5.1 cartridge
Stopping PHP 5.3 cartridge (Apache+mod_php)
Repairing links for 1 deployments
Building git ref 'master', commit 221d59e
Warning: This development build of composer is over 30 days old. It is recommended to update it by running
"/var/lib/openshift/5670889708cfed337200001b/php/usr/bin/composer self-update" to get the latest version.
Changed current directory to /var/lib/openshift/5670889708cfed337200001b/.composer
Warning: This development build of composer is over 30 days old. It is recommended to update it by running
"/var/lib/openshift/5670889708cfed337200001b/php/usr/bin/composer self-update" to get the latest version.
Using version ~8.0 for drush/drush
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drush/drush 8.0.1 requires php >=5.4.5 -> your PHP version does not satisfy that requirement.
    - drush/drush 8.0.0 requires php >=5.4.5 -> your PHP version does not satisfy that requirement.
    - Installation request for drush/drush ~8.0 -> satisfiable by drush/drush[8.0.0, 8.0.1].


Installation failed, deleting ./composer.json.
An error occurred executing 'gear postreceive' (exit code: 2)
Error message: CLIENT_ERROR: Failed to execute action hook 'pre_build' for 5670889708cfed337200001b application drupal2

For more details about the problem, try running the command again with the '--trace' option.
```

It looks like it is still attempting to install drush 8.

I'm not extremely familiar with composer, so I might be off here, but why aren't we using the composer.json file to specify the drush requirement?

You can add a marker under `.openshift/markers` called `use_composer` that will cause the php installation to call `composer install` using the `~/composer.json` file. See https://github.com/openshift/origin-server/blob/master/cartridges/openshift-origin-cartridge-php/bin/control#L143-L174

**Comment by jeffreyd** [comment]
Yeah, I just plain didn't know about the use_composer marker, and I tested against a php-5.4 cartridge because installing from the repo didn't give me a choice.  I'll fix & update, thanks. @dinhxuanvu , I'll squash the commits too.

**Comment by tiwillia** [comment]
Thanks @jeffreyd! I'm happy to review again when the changes have been made.

**Comment by jeffreyd** [comment]
Okay, I've never squashed commits before so I did my best.  This new code has been tested with the PHP-5.4 and PHP-5.3 cartridges currently available on OpenShift Online.  Changes were made to use composer.json to install drush rather than doing it manually and updates were made to work around the fact that drush isn't in the $PATH on the PHP-5.4 and PHP-5.3 cartridges.

**Comment by tiwillia** [comment]
@jeffreyd we appreciate the effort, but it doesn't look like the commits were squashed appropriately. The goal is to have a minimal number of commits for a change, preferably just one commit. You can use `git rebase -i` to interactively select commits to squash into a single commit. Check out this git-scm documentation on the subject:
  https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

If it is easier for you, you have the option to close this PR, create a new branch, make all the necessary changes, create a single commit with all changes, and create a new PR.

**Comment by jeffreyd** [comment]
I don't use this and honestly, I'm not really interested in putting more time into it.  I added a comment to the bug thread & let the people in there wanting it know they were more than welcome to fork & squash & resubmit, and I included a link to this thread also so you may be hearing from one or more of them moving forward.  Thanks!

**Pull request closed without merging**
